// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Warrior interface {
	IsWarrior()
	GetFight() string
	GetSneak() string
}

type NewNinjaInput struct {
	Name  *string `json:"name,omitempty"`
	Rank  *string `json:"rank,omitempty"`
	Fight string  `json:"fight"`
	Sneak string  `json:"sneak"`
	Hit   *string `json:"hit,omitempty"`
	Throw *string `json:"throw,omitempty"`
}

type Ninja struct {
	Name  *string          `json:"name,omitempty"`
	Rank  *string          `json:"rank,omitempty"`
	Fight string           `json:"fight"`
	Sneak string           `json:"sneak"`
	Hit   *Weapon          `json:"hit,omitempty"`
	Throw *ThrowableWeapon `json:"throw,omitempty"`
}

func (Ninja) IsWarrior()            {}
func (this Ninja) GetFight() string { return this.Fight }
func (this Ninja) GetSneak() string { return this.Sneak }

type ResponseMessage struct {
	Message string `json:"message"`
}

type ThrowableWeapon struct {
	Throw string `json:"throw"`
}

type Weapon struct {
	Hit string `json:"hit"`
}
