// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEcho() App {
	logger := NewLogger()
	echo := NewEcho(logger)
	echoHandler := NewEchoHandler(logger)
	app := NewApp(logger, echo, echoHandler)
	return app
}
